---
- hosts: spoketest
  vars_files:
    - ./adminvars.yml
  tasks:
    - name: Enable MS repo
      yum:
        name:
          - https://packages.microsoft.com/rhel/8/prod/packages-microsoft-prod.rpm
        state: present
      when: ansible_distribution == "CentOS"
    - name: Install basic system tools (CentOs)
      yum:
        name:
          - lsof
          - dstat
          - nmap
          - nmap-ncat
          - oddjob
          - oddjob-mkhomedir
          - adcli
          - samba-common-tools
          - samba-client
          - krb5-workstation
          - cifs-utils
          - autofs
          - xorg-x11-fonts-Type1
          - urw-base35-fonts
          - perl-Digest-MD5
          # - urw-base35-fonts-20170801-10
          # - urw-base35-standard-symbols-ps-fonts-20170801-10
          #- texlive-xetex
          #- texlive-xltxtra
          - git
        state: present
      when: ansible_distribution == "CentOS"
    - name: Install MS sql drivers
      environment:
        ACCEPT_EULA: "y"
      yum:
        name:
          - msodbcsql17
          - mssql-tools
        state: present
      when: ansible_distribution == "CentOS"
    - name: Install basic system tools (Ubuntu)
      apt:
        name:
          - samba-client
          - realmd
          - libnss-sss
          - libpam-sss
          - sssd
          - sssd-tools
          - adcli
          - samba-common-bin
          - oddjob
          - oddjob-mkhomedir
          - packagekit
          - autofs
          - libuser
          - texlive-latex-recommended
          - texlive-fonts-recommended
          - texlive-xetex
          - pandoc
      when: ansible_distribution == "Ubuntu"
    - name: Register with domain
      command:
        cmd: realm join -U '{{ admin_user }}'  '{{ ad_domain }}'
        stdin: "{{ password }}"
        creates: /etc/krb5.keytab
      no_log: True # Do not expose password in logs!!!!
    - name: Set adhome root dir
      ini_file:
        section: domain/ad.uit.no
        path: /etc/sssd/sssd.conf
        option: fallback_homedir
        value: /azhome/%u@%d
        mode: 0600
      notify:
        - Restart sssd
    - name: Set kerberos ticket timeout
      ini_file:
        section: domain/ad.uit.no
        path: /etc/sssd/sssd.conf
        option: krb5_renewable_lifetime
        value: 7d
        mode: 0600
      notify:
        - Restart sssd
    - name: Set kerberos ticket renew interval
      ini_file:
        section: domain/ad.uit.no
        path: /etc/sssd/sssd.conf
        option: krb5_renew_interval
        value: 500
        mode: 0600
      notify:
        - Restart sssd
    - name: Create autofs config for home dirs
      copy:
        dest: /etc/auto.master.d/azhome.autofs
        content: |
          /azhome program /etc/auto.adhome --timeout=3600
        mode: 0644
      notify:
        - Restart autofs
    - name: Create ad mount command
      copy:
        dest: /etc/auto.adhome
        src: auto.adhome
        mode: +rx
    - name: Create home share configuration
      copy:
        dest: /etc/homeshares
        src: homeshares
        mode: 0644
    - name: Mount credentials
      copy:
        dest: /etc/smbhome.conf
        src: smbhome.conf
        mode: 0600
    - name: start autofs system service
      systemd:
        name: autofs
        enabled: yes
        daemon_reload: yes
        state: started
  handlers:
    - name: Restart sssd
      ansible.builtin.systemd:
        name: sssd
        state: restarted
    - name: Restart autofs
      ansible.builtin.systemd:
        name: autofs
        state: restarted
